### PR TITLE
added liamoehlman to npm mappings

### PR DESCRIPTION
**Pull request by MauriceButler**

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
@rvagg can we deploy? :tada:

**Comment by rvagg** [comment]
:+1: but doesn't make much difference if you don't have Australia in your GitHub profile: https://github.com/liamoehlman

**Comment by MauriceButler** [comment]
@liamoehlman you should update this too...

**Comment by MauriceButler** [comment]
Thats done so hopefully next data refresh we will have the Oehlman brothers as the top and the tail of the list :)

**Comment by DamonOehlman** [comment]
awesome - if @nathanoehlman set his profile set up properly he could hover somewhere in the middle :)

**Pull request merged**
